-- ============================================================
-- ForgeIQ — Seed exercices v2 (+200 exercices)
-- Porte la bibliothèque de 89 à ~290 exercices
-- À exécuter dans Supabase → SQL Editor
-- ============================================================

INSERT INTO exercises_library (name, name_fr, slug, muscle_primary, muscle_secondary, equipment, category, force_type, difficulty, instructions, tips) VALUES

-- ══════════════════════════════════════════
-- POITRINE / CHEST
-- ══════════════════════════════════════════
('Close-Grip Bench Press', 'Développé prise serrée', 'close-grip-bench-press', ARRAY['triceps','chest'], ARRAY['front_delt'], 'barbell', 'compound', 'push', 3, 'Allonge-toi sur le banc, prise d''environ 45 cm. Descends la barre vers le bas du sternum, coudes proches du corps. Pousse en extension complète.', 'La prise serrée cible plus les triceps que le grand pectoral. Ne descends pas trop bas pour protéger les poignets.'),
('Machine Chest Press', 'Développé pectoraux machine', 'machine-chest-press', ARRAY['chest'], ARRAY['front_delt','triceps'], 'machine', 'compound', 'push', 2, 'Règle le siège pour que les poignées soient au niveau de la poitrine. Pousse jusqu''à extension quasi complète. Reviens lentement.', 'Idéal pour les débutants ou en fin de séance quand les stabilisateurs sont fatigués.'),
('Low Cable Fly', 'Écarté câble bas', 'low-cable-fly', ARRAY['chest'], ARRAY['front_delt'], 'cable', 'isolation', 'push', 2, 'Poulies en position basse. Debout au centre, amène les câbles en arc devant toi vers le haut. Pince les pectoraux en haut du mouvement.', 'Ce mouvement cible la partie supérieure des pectoraux. Garde une légère flexion des coudes tout au long.'),
('High Cable Fly', 'Écarté câble haut', 'high-cable-fly', ARRAY['chest'], ARRAY['front_delt'], 'cable', 'isolation', 'push', 2, 'Poulies en position haute. Tire les câbles vers le bas et vers l''intérieur en arc. Croise légèrement les mains en bas.', 'Cible la partie inférieure et interne des pectoraux. Visualise que tu enlaques quelqu''un.'),
('Diamond Push-Up', 'Pompe diamant', 'diamond-push-up', ARRAY['triceps'], ARRAY['chest','front_delt'], 'bodyweight', 'compound', 'push', 3, 'Mains en forme de losange sous la poitrine, index et pouces se touchent. Corps gainé, descends le buste vers les mains, remonte.', 'Les triceps sont bien plus sollicités qu''un pompe classique. Si trop difficile, fais-le sur les genoux.'),
('Pike Push-Up', 'Pompe en V inversé', 'pike-push-up', ARRAY['front_delt','shoulders'], ARRAY['triceps','chest'], 'bodyweight', 'compound', 'push', 2, 'Position pompe, lève les hanches pour former un V. Descends la tête entre les mains, remonte. Simule un développé épaules au sol.', 'Excellent préparatoire au handstand push-up. Plus les hanches sont hautes, plus les épaules travaillent.'),
('Incline Push-Up', 'Pompe inclinée', 'incline-push-up', ARRAY['chest'], ARRAY['front_delt','triceps'], 'bodyweight', 'compound', 'push', 1, 'Mains sur un banc ou une surface surélevée. Corps droit, descends la poitrine vers la surface et remonte.', 'Plus facile qu''un pompe au sol. Parfait pour débuter ou en échauffement.'),
('Decline Push-Up', 'Pompe déclinée', 'decline-push-up', ARRAY['upper_chest'], ARRAY['front_delt','triceps'], 'bodyweight', 'compound', 'push', 2, 'Pieds sur un banc, mains au sol. Corps droit, descends la poitrine vers le sol. Cible la partie haute des pecs.', 'L''angle décliné met plus l''accent sur les fibres supérieures des pectoraux.'),
('Dumbbell Hex Press', 'Hex Press haltères', 'dumbbell-hex-press', ARRAY['chest'], ARRAY['triceps'], 'dumbbell', 'isolation', 'push', 2, 'Allongé sur le banc, haltères en prise neutre se touchant. Pousse en maintenant constamment la pression entre les deux haltères. Descends lentement.', 'La tension constante entre les haltères maximise la contraction interne des pectoraux.'),
('Machine Fly', 'Écarté pectoraux machine', 'machine-fly', ARRAY['chest'], ARRAY['front_delt'], 'machine', 'isolation', 'push', 1, 'Assis sur la machine, coudes légèrement fléchis. Ramène les bras vers l''avant et l''intérieur en arc. Maintiens 1 seconde en contraction.', 'Excellent en fin de séance pour finir les pectoraux sans fatiguer les stabilisateurs.'),

-- ══════════════════════════════════════════
-- DOS / BACK
-- ══════════════════════════════════════════
('T-Bar Row', 'Rowing barre en T', 't-bar-row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt','traps'], 'barbell', 'compound', 'pull', 3, 'Barre coincée dans un angle ou sur un support dédié. Penché à 45°, saisit la barre avec une prise en V, tire vers le ventre. Garde le dos droit.', 'Excellent pour l''épaisseur du dos. Concentre-toi sur tirer avec les coudes, pas avec les bras.'),
('Chest-Supported Row', 'Rowing soutenu poitrine', 'chest-supported-row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'machine', 'compound', 'pull', 2, 'Allonge la poitrine sur le support incliné. Tire les poignées vers toi en écartant les coudes. La poitrine soutenue élimine la triche lombaire.', 'La position soutenue isole parfaitement le dos et évite la compensation du bas du dos.'),
('Straight-Arm Pulldown', 'Tirage bras tendus poulie haute', 'straight-arm-pulldown', ARRAY['lats'], ARRAY['triceps','rear_delt'], 'cable', 'isolation', 'pull', 2, 'Debout face à la poulie haute, bras tendus. Tire la barre vers les cuisses en gardant les coudes verrouillés. Sens la contraction des lats.', 'Un des meilleurs exercices d''isolation pour les grands dorsaux. Visualise que tu écrases quelque chose sous tes bras.'),
('Single-Arm Cable Row', 'Rowing câble unilatéral', 'single-arm-cable-row', ARRAY['lats','mid_back'], ARRAY['biceps'], 'cable', 'compound', 'pull', 2, 'Assis ou debout face à la poulie basse, tire d''une main vers la hanche. Permet une rotation du tronc pour plus d''amplitude.', 'Le travail unilatéral corrige les déséquilibres entre côtés. Tire en pensant à ramener le coude dans la poche arrière.'),
('Neutral Grip Pull-Up', 'Traction prise neutre', 'neutral-grip-pull-up', ARRAY['lats','biceps'], ARRAY['mid_back','brachialis'], 'bodyweight', 'compound', 'pull', 3, 'Mains en prise neutre (paumes face à face). Monte jusqu''au menton au-dessus de la barre. Descends en contrôle.', 'La prise neutre est souvent plus forte que la pronation et réduit le stress sur les coudes.'),
('Inverted Row', 'Rowing inversé', 'inverted-row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'bodyweight', 'compound', 'pull', 2, 'Barre à hauteur de hanche, corps incliné sous la barre. Tire la poitrine vers la barre en gardant le corps gainé. Varie l''inclinaison pour ajuster la difficulté.', 'Plus tu es horizontal, plus c''est difficile. Excellent pour les débutants qui ne font pas encore de tractions.'),
('Pendlay Row', 'Rowing Pendlay', 'pendlay-row', ARRAY['mid_back','lats'], ARRAY['biceps','traps'], 'barbell', 'compound', 'pull', 4, 'Corps parallèle au sol, barre au sol. Explosivité : tire la barre jusqu''au sternum de manière explosive, repose-la entièrement au sol entre chaque rep.', 'Plus strict que le rowing barre classique. La barre part du sol à chaque rep, ce qui développe la puissance du dos.'),
('Rack Pull', 'Tirage de rack', 'rack-pull', ARRAY['mid_back','traps'], ARRAY['lats','glutes','hamstrings'], 'barbell', 'compound', 'pull', 3, 'Barre réglée au niveau des genoux dans un rack. Soulève comme un soulevé de terre depuis cette position. Idéal pour surcharger le dos supérieur.', 'Permet des charges plus lourdes qu''un soulevé de terre complet. Excellent pour renforcer la partie supérieure du dos.'),
('Cable Pullover', 'Pullover câble', 'cable-pullover', ARRAY['lats'], ARRAY['chest','triceps'], 'cable', 'isolation', 'pull', 2, 'Debout, dos à la poulie haute. Penché légèrement, tire la barre en arc vers les cuisses, bras tendus. Sens l''étirement des lats.', 'Maintient une tension constante sur les lats contrairement au haltère. Excellent pour finir le dos.'),
('Dumbbell Pullover', 'Pullover haltère', 'dumbbell-pullover', ARRAY['lats','chest'], ARRAY['triceps'], 'dumbbell', 'isolation', 'pull', 2, 'Allongé perpendiculairement sur un banc, nuque sur le banc. Haltère à deux mains au-dessus de la poitrine, descends-le en arc derrière la tête.', 'Exercice rare qui sollicite à la fois les lats et les pectoraux. Garde les coudes légèrement fléchis.'),
('Meadows Row', 'Rowing Meadows', 'meadows-row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', 'compound', 'pull', 3, 'Barre coincée dans un angle, debout de côté. Saisit l''extrémité de la barre et tire vers la hanche. Amplitude maximale en rotation.', 'Inventé par John Meadows, cet exercice offre une amplitude exceptionnelle et cible parfaitement les lats.'),
('Banded Pull-Apart', 'Écartement élastique', 'banded-pull-apart', ARRAY['rear_delt','upper_back'], ARRAY['rotator_cuff','traps'], 'band', 'isolation', 'pull', 1, 'Élastique tenu à bout de bras devant soi. Tire l''élastique en l''écartant de chaque côté jusqu''à toucher la poitrine. Lent et contrôlé.', 'Exercice de santé des épaules par excellence. Fait-le en échauffement ou entre les séries de développé.'),

-- ══════════════════════════════════════════
-- ÉPAULES / SHOULDERS
-- ══════════════════════════════════════════
('Landmine Press', 'Développé landmine', 'landmine-press', ARRAY['front_delt','upper_chest'], ARRAY['triceps','traps'], 'barbell', 'compound', 'push', 2, 'Barre coincée dans un angle au sol. Tiens l''extrémité à une ou deux mains à hauteur d''épaule, pousse en arc vers le haut.', 'Mouvement guidé en arc qui ménage les épaules. Excellent pour les personnes avec des douleurs d''épaule au développé classique.'),
('Machine Shoulder Press', 'Développé épaule machine', 'machine-shoulder-press', ARRAY['shoulders','front_delt'], ARRAY['triceps','traps'], 'machine', 'compound', 'push', 2, 'Régle le siège à la bonne hauteur. Pousse les poignées au-dessus de la tête jusqu''à quasi-extension. Redescends lentement.', 'La machine guide le mouvement et sécurise le dos. Parfait pour les débutants ou après des exercices libres.'),
('Push Press', 'Développé poussé', 'push-press', ARRAY['front_delt','shoulders'], ARRAY['triceps','traps','quads'], 'barbell', 'compound', 'push', 3, 'Barre sur les épaules, légère flexion des genoux, pousse explosif vers le haut en utilisant l''élan des jambes. Verrouille les bras en haut.', 'Permet de soulever plus lourd qu''un strict press. La force des jambes aide à initier le mouvement.'),
('Cable Lateral Raise', 'Élévation latérale câble', 'cable-lateral-raise', ARRAY['side_delt'], ARRAY['traps'], 'cable', 'isolation', 'push', 2, 'Poulie basse sur le côté. Tire le câble vers le haut latéralement jusqu''à hauteur d''épaule. Le câble maintient la tension en bas contrairement aux haltères.', 'Meilleure tension en bas du mouvement que les haltères. Excellent pour finir les deltoïdes.'),
('Machine Lateral Raise', 'Élévation latérale machine', 'machine-lateral-raise', ARRAY['side_delt'], ARRAY['traps'], 'machine', 'isolation', 'push', 1, 'Assis sur la machine, bras sur les coussins. Lève les bras latéralement jusqu''à hauteur d''épaule. Redescends lentement.', 'La machine offre une résistance constante idéale pour les deltoïdes. Concentre-toi sur la contraction.'),
('Bradford Press', 'Bradford Press', 'bradford-press', ARRAY['front_delt','side_delt'], ARRAY['traps','triceps'], 'barbell', 'compound', 'push', 3, 'Alterner barre devant et derrière la tête sans jamais verrouiller les coudes. Mouvement continu semi-circulaire.', 'Excellent exercice de volume pour les épaules. Ne verrouille jamais les coudes pour maintenir la tension.'),
('Y-T-W Raise', 'Élévation Y-T-W', 'y-t-w-raise', ARRAY['rear_delt','upper_back'], ARRAY['rotator_cuff','traps'], 'dumbbell', 'isolation', 'pull', 2, 'Allongé sur un banc incliné à plat ventre. Effectue 3 positions : Y (bras à 45°), T (bras à 90°), W (coudes pliés à 90°). Poids très légers.', 'Exercice de rééducation et renforcement des rotateurs. Utilise des poids très légers. Mouvement de santé.'),
('Plate Front Raise', 'Élévation frontale disque', 'plate-front-raise', ARRAY['front_delt'], ARRAY['side_delt','traps'], 'barbell', 'isolation', 'push', 2, 'Tiens un disque à deux mains, bras tendus. Lève le disque devant toi jusqu''à hauteur d''épaule. Redescends lentement.', 'Le disque distribue le poids différemment des haltères. La prise neutre varie le stimulus.'),
('Behind-Neck Press', 'Développé nuque', 'behind-neck-press', ARRAY['side_delt','front_delt'], ARRAY['triceps','traps'], 'barbell', 'compound', 'push', 4, 'Barre derrière la nuque sur les trapèzes. Pousse vers le haut jusqu''à extension. Nécessite une bonne mobilité d''épaule.', 'Exercice avancé avec risque si mal exécuté. Déconseillé si tu as des douleurs d''épaule ou un manque de mobilité.'),

-- ══════════════════════════════════════════
-- BICEPS
-- ══════════════════════════════════════════
('Preacher Curl', 'Curl préacher', 'preacher-curl', ARRAY['biceps'], ARRAY['brachialis'], 'barbell', 'isolation', 'pull', 2, 'Bras posés sur le coussin incliné du pupitre. Curl complet depuis l''extension jusqu''à la contraction maximale. Pas d''élan possible.', 'Le pupitre élimine toute triche. Concentre-toi sur la partie basse du mouvement pour l''étirement.'),
('Incline Dumbbell Curl', 'Curl haltère incliné', 'incline-dumbbell-curl', ARRAY['biceps'], ARRAY['brachialis'], 'dumbbell', 'isolation', 'pull', 2, 'Assis sur un banc incliné à 60°. Les bras pendent librement. Curl un haltère à la fois ou ensemble depuis l''extension complète.', 'L''inclinaison pré-étire les biceps en bas du mouvement. Excellent pour développer le pic du biceps.'),
('Spider Curl', 'Spider Curl', 'spider-curl', ARRAY['biceps'], ARRAY['brachialis'], 'barbell', 'isolation', 'pull', 2, 'Allongé sur un banc incliné à plat ventre, bras pendants perpendiculaires au sol. Curl les haltères ou la barre vers le visage.', 'Comme le preacher mais avec encore moins de triche possible. Le pic de contraction est extrême.'),
('Cable Hammer Curl', 'Curl marteau câble', 'cable-hammer-curl', ARRAY['brachialis','biceps'], ARRAY['forearms'], 'cable', 'isolation', 'pull', 2, 'Poulie basse, corde ou poignée neutre. Curl en prise neutre (pouce vers le haut) jusqu''à la contraction.', 'La corde permet un mouvement naturel du poignet. Cible particulièrement le brachialis et la longue portion.'),
('Reverse Curl', 'Curl inversé', 'reverse-curl', ARRAY['brachialis','forearms'], ARRAY['biceps'], 'barbell', 'isolation', 'pull', 2, 'Prise en pronation (dos de la main vers le haut). Curl la barre jusqu''à l''horizontale. Elbows fixes.', 'La prise inversée cible le brachialis et les extenseurs du poignet. Aide à équilibrer le développement du bras.'),
('Zottman Curl', 'Curl Zottman', 'zottman-curl', ARRAY['biceps','brachialis','forearms'], ARRAY[]::text[], 'dumbbell', 'isolation', 'pull', 2, 'Curl en supination (paume vers le haut) à la montée. En haut, tourne en pronation (paume vers le bas). Redescends en pronation. Retourne en supination en bas.', 'Un exercice qui cible les biceps à la montée et les brachialis à la descente. Double bénéfice en une répétition.'),
('Machine Curl', 'Curl machine', 'machine-curl', ARRAY['biceps'], ARRAY['brachialis'], 'machine', 'isolation', 'pull', 1, 'Assis face à la machine, coudes sur le coussin. Curl jusqu''à contraction maximale. Redescends lentement.', 'Parfait pour les débutants ou en drop set en fin de séance. La machine maintient la forme parfaite.'),
('Cross-Body Curl', 'Curl croisé', 'cross-body-curl', ARRAY['brachialis','biceps'], ARRAY['forearms'], 'dumbbell', 'isolation', 'pull', 1, 'Curl l''haltère en le ramenant vers l''épaule opposée plutôt que vers l''épaule du même côté. Prise marteau.', 'Cible particulièrement le brachialis et donne de l''épaisseur au bras entre les deux têtes.'),
('21s Curl', 'Curl 21s', 'curl-21s', ARRAY['biceps'], ARRAY['brachialis'], 'barbell', 'isolation', 'pull', 2, '7 reps du bas jusqu''au milieu (bras à 90°). Puis 7 reps du milieu jusqu''en haut. Puis 7 reps complètes. Sans pause.', 'Technique d''intensification qui épuise les biceps en 3 phases. Réduis le poids de 30% vs ton curl normal.'),

-- ══════════════════════════════════════════
-- TRICEPS
-- ══════════════════════════════════════════
('Tricep Kickback', 'Extension tricep arrière', 'tricep-kickback', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', 'isolation', 'push', 2, 'Penché en avant, bras parallèle au sol. Étends l''avant-bras vers l''arrière jusqu''à l''horizontale. Maintiens 1 seconde.', 'Excellent pour la longue portion du triceps. Garde le bras parallèle au sol pendant tout le mouvement.'),
('Cable Overhead Tricep Extension', 'Extension tricep nuque câble', 'cable-overhead-tricep-extension', ARRAY['triceps'], ARRAY[]::text[], 'cable', 'isolation', 'push', 2, 'Poulie haute derrière toi, corde ou barre. Mains derrière la tête, étends les avant-bras vers le haut. Maintiens l''étirement en bas.', 'L''étirement en position allongée maximise le travail de la longue portion du triceps.'),
('Single-Arm Pushdown', 'Tirage unilatéral tricep', 'single-arm-pushdown', ARRAY['triceps'], ARRAY[]::text[], 'cable', 'isolation', 'push', 2, 'Poulie haute, une main sur la poignée. Pousse vers le bas en gardant le coude fixe près du corps. Contraction complète en bas.', 'Le travail unilatéral permet de corriger les déséquilibres. Commence par le bras le plus faible.'),
('Bench Dip', 'Dip sur banc', 'bench-dip', ARRAY['triceps'], ARRAY['chest','front_delt'], 'bodyweight', 'compound', 'push', 2, 'Mains sur un banc derrière toi, pieds posés devant. Descends en fléchissant les coudes jusqu''à 90°, remonte en poussant.', 'Ajoute du poids sur les cuisses pour progresser. Plus les pieds sont loin, plus c''est difficile.'),
('Reverse Grip Pushdown', 'Tirage prise inversée tricep', 'reverse-grip-pushdown', ARRAY['triceps'], ARRAY['forearms'], 'cable', 'isolation', 'push', 2, 'Poulie haute, prise en supination (paumes vers le haut). Pousse la barre vers le bas. Coudes fixes.', 'La prise inversée met plus l''accent sur le chef médial du triceps. Excellent pour l''épaisseur du bras.'),
('JM Press', 'JM Press', 'jm-press', ARRAY['triceps'], ARRAY['chest'], 'barbell', 'compound', 'push', 3, 'Allongé sur le banc, prise serrée. Descends la barre vers la gorge en gardant les coudes à 45°, comme un hybride skullcrusher/développé prise serrée.', 'Exercice avancé pour les triceps inventé par JM Blakley. Nécessite une bonne maîtrise technique.'),
('Tricep Machine', 'Machine tricep', 'tricep-machine', ARRAY['triceps'], ARRAY[]::text[], 'machine', 'isolation', 'push', 1, 'Assis, bras sur les coussins. Pousse les poignées vers le bas jusqu''à extension complète. Redescends lentement.', 'Machine simple et efficace. Parfait en fin de séance pour finir les triceps sans risque.'),
('Tate Press', 'Tate Press', 'tate-press', ARRAY['triceps'], ARRAY['chest'], 'dumbbell', 'isolation', 'push', 3, 'Allongé sur le banc, haltères au-dessus de la poitrine pointes vers le haut. Descends les pointes vers la poitrine en gardant les coudes au-dessus. Remonte.', 'Exercice avancé qui cible les triceps avec une mécanique unique. Nécessite de la coordination.'),

-- ══════════════════════════════════════════
-- JAMBES / LEGS
-- ══════════════════════════════════════════
('Hack Squat', 'Hack Squat machine', 'hack-squat-machine', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'machine', 'compound', 'legs', 2, 'Dos contre le dossier, épaules sous les coussins, pieds à largeur d''épaules sur la plateforme. Descends jusqu''à 90° ou plus, remonte en poussant.', 'La position guidée met l''accent sur les quadriceps. Varie l''écartement des pieds pour cibler différentes zones.'),
('Box Squat', 'Squat sur box', 'box-squat', ARRAY['quads','glutes'], ARRAY['hamstrings','lower_back'], 'barbell', 'compound', 'legs', 3, 'Barre sur le dos, box derrière toi. Descends jusqu''à t''asseoir sur la box, pause 1 seconde, remonte explosiviment.', 'Excellent pour apprendre la profondeur et développer la force explosive depuis le bas. La pause élimine l''effet ressort.'),
('Pause Squat', 'Squat pause', 'pause-squat', ARRAY['quads','glutes'], ARRAY['hamstrings','lower_back'], 'barbell', 'compound', 'legs', 4, 'Squat classique mais avec 2-3 secondes de pause dans le trou. Reste dans la position basse puis remonte explosiviment.', 'Élimine l''élan et renforce le point faible du squat. Réduis le poids de 20% vs ton squat normal.'),
('Sumo Deadlift', 'Soulevé de terre sumo', 'sumo-deadlift', ARRAY['glutes','hamstrings'], ARRAY['quads','lower_back','traps'], 'barbell', 'compound', 'legs', 3, 'Écartement très large des pieds, pieds pointés à 45°. Mains à l''intérieur des genoux. Dos droit, tire la barre en poussant le sol.', 'La position sumo réduit le trajet de la barre et met plus l''accent sur les fessiers et l''intérieur des cuisses.'),
('Stiff-Leg Deadlift', 'Soulevé de terre jambes tendues', 'stiff-leg-deadlift', ARRAY['hamstrings','lower_back'], ARRAY['glutes'], 'barbell', 'isolation', 'legs', 3, 'Jambes quasi tendues (légère flexion). Penche-toi en avant en gardant le dos droit, barre proche des jambes. Remonte en contractant les ischios.', 'Excellent pour l''étirement des ischios. Ne pas confondre avec le Romanian Deadlift - la différence est dans la flexion des genoux.'),
('Good Morning', 'Good Morning', 'good-morning', ARRAY['lower_back','hamstrings'], ARRAY['glutes'], 'barbell', 'isolation', 'legs', 3, 'Barre sur le dos comme un squat. Penche-toi en avant depuis les hanches jusqu''à ce que le torse soit presque parallèle au sol. Reviens en contractant les lombaires.', 'Renforce énormément les ischios et le bas du dos. Commence TRÈS léger, la technique est primordiale.'),
('Glute Bridge', 'Pont fessier', 'glute-bridge', ARRAY['glutes'], ARRAY['hamstrings','lower_back'], 'bodyweight', 'isolation', 'legs', 1, 'Allongé sur le dos, genoux fléchis. Pousse les hanches vers le haut en contractant les fessiers. Maintiens 2 secondes en haut.', 'Exercice de base pour activer les fessiers. Ajoute un haltère ou une barre sur les hanches pour progresser.'),
('Cable Kickback', 'Extension fesse câble', 'cable-kickback', ARRAY['glutes'], ARRAY['hamstrings'], 'cable', 'isolation', 'legs', 1, 'Face à la poulie basse, cheville dans la sangle. Recule la jambe en extension en contractant le fessier. Maintiens 1 seconde.', 'Isole parfaitement les fessiers. Garde le dos droit et ne prends pas d''élan. Travaille lentement.'),
('Abductor Machine', 'Machine abducteur', 'abductor-machine', ARRAY['hip_abductors','glutes'], ARRAY[]::text[], 'machine', 'isolation', 'legs', 1, 'Assis sur la machine, cuisses contre les coussins. Écarte les jambes vers l''extérieur contre la résistance. Reviens lentement.', 'Cible les abducteurs et la face externe des fessiers. Excellent pour la stabilité du genou.'),
('Adductor Machine', 'Machine adducteur', 'adductor-machine', ARRAY['hip_abductors'], ARRAY['quads'], 'machine', 'isolation', 'legs', 1, 'Assis sur la machine, coussins contre l''intérieur des genoux. Ramène les jambes vers l''intérieur. Redescends lentement.', 'Cible la face interne des cuisses. Important pour l''équilibre musculaire et la prévention des blessures.'),
('Nordic Curl', 'Curl nordique', 'nordic-curl', ARRAY['hamstrings'], ARRAY['glutes'], 'bodyweight', 'isolation', 'legs', 4, 'Genoux au sol, pieds bloqués. Descends lentement en avant en freinant avec les ischios. Pousse avec les mains pour remonter si nécessaire.', 'Un des meilleurs exercices pour prévenir les blessures aux ischios. Extrêmement difficile - commence avec une bande élastique pour l''assistance.'),
('Sissy Squat', 'Sissy Squat', 'sissy-squat', ARRAY['quads'], ARRAY[]::text[], 'bodyweight', 'isolation', 'legs', 3, 'Tendu à un support, penche le corps en arrière en montant sur la pointe des pieds, genoux vers l''avant. Descends et remonte.', 'Isole les quadriceps de manière unique. Nécessite un bon équilibre. La flexion tibiale maximise le travail des quads.'),
('Wall Sit', 'Chaise murale', 'wall-sit', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'bodyweight', 'isolation', 'legs', 2, 'Dos au mur, descends jusqu''à 90° aux genoux. Maintiens la position. Durée : 30 à 90 secondes.', 'Excellent exercice isométrique pour les quadriceps. Idéal pour le cardio musculaire sans impact.'),
('Step-Up', 'Montée sur box', 'step-up', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', 'compound', 'legs', 2, 'Face à une box ou un banc. Monte en posant un pied entier sur la surface, pousse pour monter. Descends en contrôle.', 'Excellent pour le travail unilatéral. Évite de prendre de l''élan avec le pied arrière pour isoler la jambe qui travaille.'),
('Single-Leg Press', 'Presse unijambiste', 'single-leg-press', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'machine', 'compound', 'legs', 2, 'Presse classique mais avec une seule jambe. Réduis le poids de moitié. Pousse jusqu''à quasi-extension, reviens jusqu''à 90°.', 'Corrige les déséquilibres entre jambes. Souvent, la jambe dominante est bien plus forte. Commence par la jambe faible.'),
('Single-Leg Romanian Deadlift', 'Soulevé roumain unijambiste', 'single-leg-romanian-deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'dumbbell', 'isolation', 'legs', 3, 'Debout sur une jambe, haltère dans la main opposée. Penche-toi en avant en étendant la jambe libre derrière. Reviens en poussant le sol.', 'Excellent pour la proprioception et l''équilibre. La jambe libre aide à l''équilibre. Commence léger pour maîtriser le mouvement.'),
('Banded Hip Thrust', 'Hip Thrust avec élastique', 'banded-hip-thrust', ARRAY['glutes'], ARRAY['hamstrings','lower_back'], 'band', 'compound', 'legs', 2, 'Dos contre un banc, élastique sur les hanches. Pousse les hanches vers le haut en contractant les fessiers. Maintiens 2 secondes.', 'L''élastique ajoute de la résistance en haut du mouvement où c''est le plus difficile. Variante sans barre pour les débutants.'),
('Deficit Deadlift', 'Soulevé de terre en déficit', 'deficit-deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back','quads'], 'barbell', 'compound', 'legs', 4, 'Debout sur des plaques (5-10 cm). Soulevé de terre depuis cette position plus basse. Augmente l''amplitude du mouvement.', 'Renforce le bas du soulevé de terre. Améliore le passage au niveau des genoux. Réduis le poids vs un deadlift normal.'),
('Trap Bar Deadlift', 'Soulevé de terre barre hexagonale', 'trap-bar-deadlift', ARRAY['quads','hamstrings','glutes'], ARRAY['lower_back','traps'], 'barbell', 'compound', 'legs', 3, 'Dans la barre hexagonale, prise neutre. Corps entre les poids. Soulevé de terre avec une position plus verticale du tronc.', 'Plus sûr pour le dos que la barre droite. Excellent pour les débutants et ceux avec des problèmes lombaires.'),
('Curtsy Lunge', 'Fente croisée', 'curtsy-lunge', ARRAY['glutes','quads'], ARRAY['hip_abductors'], 'bodyweight', 'compound', 'legs', 2, 'Debout, croise la jambe arrière derrière la jambe avant en diagonale et descends. Reviens à la position initiale.', 'Travaille l''abduction de hanche et les fessiers latéraux. Excellent pour la stabilité du bassin.'),
('Reverse Lunge', 'Fente arrière', 'reverse-lunge', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'bodyweight', 'compound', 'legs', 2, 'Debout, recule un pied et descends le genou arrière près du sol. Remonte en poussant avec le pied avant.', 'Plus douce pour les genoux que la fente avant. L''instabilité est réduite car le genou avant reste plus stable.'),
('Tibialis Raise', 'Relevé de tibia', 'tibialis-raise', ARRAY['calves'], ARRAY[]::text[], 'bodyweight', 'isolation', 'legs', 1, 'Dos au mur, talons à 30 cm du mur. Relève les pointes de pied vers le tibia aussi haut que possible. Redescends lentement.', 'Renforce le tibial antérieur, muscle souvent négligé qui prévient les douleurs de shin splints.'),
('Seated Calf Raise Machine', 'Machine mollets assis', 'seated-calf-raise-machine', ARRAY['calves'], ARRAY[]::text[], 'machine', 'isolation', 'legs', 1, 'Assis, coussin sur les genoux. Monte sur la pointe des pieds au maximum, maintiens 1 seconde, descends jusqu''à l''étirement complet.', 'La position assise cible davantage le soléaire (muscle profond des mollets) que le debout.'),
('Leg Press Calf Raise', 'Mollets à la presse', 'leg-press-calf-raise', ARRAY['calves'], ARRAY[]::text[], 'machine', 'isolation', 'legs', 1, 'En position presse, jambes quasi tendues. Pousse avec les pointes des pieds uniquement. Amplitude complète vers le bas.', 'Permet de charger davantage les mollets qu''un simple relevé de talons. Utilise une charge plus lourde.'),
('Frog Pump', 'Pompe grenouille', 'frog-pump', ARRAY['glutes'], ARRAY[]::text[], 'bodyweight', 'isolation', 'legs', 1, 'Allongé sur le dos, plantes des pieds ensemble, genoux écartés. Pousse les hanches vers le haut en contractant les fessiers. Répétitions rapides.', 'Active parfaitement les fessiers sans matériel. Idéal pour l''activation avant une séance ou entre deux exercices.'),
('Donkey Kick', 'Coup de pied âne', 'donkey-kick', ARRAY['glutes'], ARRAY['lower_back'], 'bodyweight', 'isolation', 'legs', 1, 'À quatre pattes, dos à plat. Lance un pied vers le plafond en gardant le genou fléchi à 90°. Contracte le fessier en haut.', 'Exercice d''activation des fessiers par excellence. Ajoute un élastique autour des genoux pour plus de résistance.'),
('Fire Hydrant', 'Borne incendie', 'fire-hydrant', ARRAY['hip_abductors','glutes'], ARRAY[]::text[], 'bodyweight', 'isolation', 'legs', 1, 'À quatre pattes. Lève le genou sur le côté en gardant la flexion à 90°, comme un chien qui urine. Contrôle la descente.', 'Active les abducteurs et les fessiers latéraux. Excellent en activation ou en réhabilitation.'),
('Clamshell', 'Palourde avec élastique', 'clamshell', ARRAY['hip_abductors','glutes'], ARRAY[]::text[], 'band', 'isolation', 'legs', 1, 'Allongé sur le côté, élastique autour des genoux, hanches à 45°. Ouvre le genou supérieur comme une palourde contre l''élastique.', 'Exercice de rééducation et d''activation des abducteurs. Indispensable si tu as des problèmes de genou valgus.'),
('Banded Squat Walk', 'Marche squat élastique', 'banded-squat-walk', ARRAY['hip_abductors','glutes'], ARRAY['quads'], 'band', 'compound', 'legs', 2, 'Élastique autour des chevilles ou des genoux. Position demi-squat. Marche latéralement en gardant la position basse et la tension sur l''élastique.', 'Active les abducteurs en mouvement fonctionnel. Idéal en échauffement avant squats ou hip thrusts.'),

-- ══════════════════════════════════════════
-- ABDOMINAUX / ABS
-- ══════════════════════════════════════════
('Hollow Body Hold', 'Gainage creux', 'hollow-body-hold', ARRAY['abs','core'], ARRAY['hip_flexors'], 'bodyweight', 'isolation', 'core', 3, 'Allongé sur le dos, bras tendus au-dessus de la tête, jambes tendues à 30 cm du sol. Corps en forme de banane creuse. Maintiens.', 'Base de la gymnastique. Si trop difficile, remonte les jambes ou plie les bras. 20-30 secondes pour commencer.'),
('Hanging Leg Raise', 'Relevé de jambes suspendu', 'hanging-leg-raise', ARRAY['abs','hip_flexors'], ARRAY['forearms'], 'bodyweight', 'isolation', 'core', 3, 'Suspendu à la barre, jambes tendues. Lève les jambes jusqu''à l''horizontale ou plus. Descends sans balancer.', 'Exercice exigeant pour les abdos et les fléchisseurs. Commence les genoux fléchis si trop difficile.'),
('Windshield Wipers', 'Essuie-glaces', 'windshield-wipers', ARRAY['obliques','abs'], ARRAY['hip_flexors'], 'bodyweight', 'isolation', 'core', 4, 'Suspendu à la barre, jambes tendues à 90°. Bascule les jambes d''un côté puis de l''autre comme des essuie-glaces.', 'Exercice très avancé pour les obliques. Garde les jambes le plus tendues possible et contrôle le mouvement.'),
('Dragon Flag', 'Dragon Flag', 'dragon-flag', ARRAY['abs','core'], ARRAY['lower_back','hip_flexors'], 'bodyweight', 'compound', 'core', 5, 'Allongé sur un banc, mains derrière la tête sous le banc. Corps droit, monte les jambes et le corps en ne gardant que les épaules au sol. Descends en contrôle.', 'Exercice emblématique de Bruce Lee. Extrêmement difficile. Commence par les dragon flag excentriques uniquement.'),
('Side Plank', 'Gainage latéral', 'side-plank', ARRAY['obliques'], ARRAY['core','hip_abductors'], 'bodyweight', 'isolation', 'core', 2, 'Allongé sur le côté, appui sur un coude. Corps en ligne droite, hanches soulevées. Maintiens. Variante : avec rotation du bras libre.', 'Renforce les obliques et les stabilisateurs latéraux. Ajoute une rotation du bras libre vers le plafond pour plus de défi.'),
('Pallof Press', 'Press Pallof', 'pallof-press', ARRAY['obliques','core'], ARRAY['abs'], 'cable', 'isolation', 'core', 2, 'Debout de côté par rapport à la poulie. Poignée à la poitrine. Pousse les bras en extension, maintiens 2 secondes, reviens. Le câble tente de te faire tourner.', 'Exercice anti-rotation par excellence. Renforce le gainage latéral de manière fonctionnelle. Excellent pour les sportifs.'),
('Dead Bug', 'Dead Bug', 'dead-bug', ARRAY['abs','core'], ARRAY['hip_flexors'], 'bodyweight', 'isolation', 'core', 2, 'Allongé sur le dos, bras tendus vers le plafond, genoux à 90° dans l''air. Étends simultanément le bras droit et la jambe gauche vers le sol. Reviens. Alterne.', 'Exercice de contrôle moteur qui renforce la coordination et le gainage profond. Garde le bas du dos collé au sol.'),
('Bird Dog', 'Bird Dog', 'bird-dog', ARRAY['core','lower_back'], ARRAY['glutes','shoulders'], 'bodyweight', 'isolation', 'core', 1, 'À quatre pattes, dos plat. Étends simultanément le bras droit et la jambe gauche. Maintiens 2 secondes. Alterne.', 'Exercice de stabilisation lombaire. Parfait pour les personnes avec des douleurs de dos ou en prévention.'),
('Mountain Climber', 'Grimpeur', 'mountain-climber', ARRAY['core','abs'], ARRAY['hip_flexors','chest'], 'bodyweight', 'cardio', 'core', 2, 'Position de pompe. Ramène alternativement les genoux vers la poitrine de manière dynamique. Garde les hanches basses.', 'Excellent exercice cardio-musculaire. Plus tu vas vite, plus l''aspect cardio domine. Lent = plus d''abos.'),
('V-Up', 'V-Up', 'v-up', ARRAY['abs','hip_flexors'], ARRAY[]::text[], 'bodyweight', 'isolation', 'core', 3, 'Allongé sur le dos, bras tendus derrière la tête. Lève simultanément les jambes tendues et le buste pour former un V. Redescends sans toucher complètement le sol.', 'Travaille toute la sangle abdominale en même temps. Si trop difficile, plie légèrement les genoux.'),
('Bicycle Crunch', 'Crunch vélo', 'bicycle-crunch', ARRAY['obliques','abs'], ARRAY['hip_flexors'], 'bodyweight', 'isolation', 'core', 2, 'Allongé sur le dos, mains derrière la tête. Ramène le genou droit vers le coude gauche en tournant le buste. Alterne de manière fluide.', 'Un des exercices les plus efficaces pour les obliques selon les études EMG. Contrôle le mouvement, ne tire pas sur le cou.'),
('Decline Crunch', 'Crunch décliné', 'decline-crunch', ARRAY['abs'], ARRAY[]::text[], 'bodyweight', 'isolation', 'core', 2, 'Assis sur un banc décliné, pieds bloqués. Monte le buste vers les genoux en arrondissant le dos. Redescends en contrôle.', 'Le décliné augmente la résistance et l''amplitude vs un crunch plat. Ajoute du poids pour progresser.'),
('Reverse Crunch', 'Crunch inversé', 'reverse-crunch', ARRAY['abs'], ARRAY['hip_flexors'], 'bodyweight', 'isolation', 'core', 2, 'Allongé sur le dos, jambes à 90°. Tire les genoux vers la poitrine en soulevant les hanches du sol. Redescends lentement.', 'Cible la partie inférieure des abdominaux mieux qu''un crunch classique. Évite l''élan, contrôle le mouvement.'),
('Seated Knee Tuck', 'Relevé de genoux assis', 'seated-knee-tuck', ARRAY['abs','hip_flexors'], ARRAY[]::text[], 'bodyweight', 'isolation', 'core', 2, 'Assis sur un banc, mains de chaque côté. Penche le buste en arrière et étends les jambes. Ramène les genoux vers la poitrine.', 'Bon exercice pour les abdos inférieurs. Peut se faire sur une parallette pour plus d''amplitude.'),
('Cable Woodchop', 'Bûcheron câble', 'cable-woodchop', ARRAY['obliques','core'], ARRAY['shoulders','abs'], 'cable', 'isolation', 'core', 2, 'Poulie haute sur le côté. Tire le câble en diagonale vers le bas et l''opposé en faisant pivoter le tronc. Contrôle la montée.', 'Mouvement rotatif fonctionnel. Excellent pour les sports de raquette, golf, boxe. Renforce les obliques en rotation.'),
('GHD Sit-Up', 'Sit-Up sur GHD', 'ghd-sit-up', ARRAY['abs','hip_flexors'], ARRAY['lower_back'], 'machine', 'compound', 'core', 3, 'Sur la machine GHD, cuisses sur les coussins, pieds bloqués. Descends le buste vers le bas (extension du dos), remonte en position assise.', 'Exercice complet de la chaîne antérieure. L''amplitude est supérieure à un crunch normal. Attention aux courbatures abdominales.'),

-- ══════════════════════════════════════════
-- MOBILITÉ / MOBILITY
-- ══════════════════════════════════════════
('Hip Flexor Stretch', 'Étirement fléchisseur de hanche', 'hip-flexor-stretch', ARRAY['hip_flexors'], ARRAY[]::text[], 'bodyweight', 'mobility', 'legs', 1, 'Un genou au sol en fente. Pousse les hanches vers l''avant jusqu''à sentir l''étirement à l''avant de la cuisse arrière. Maintiens 30-60 secondes.', 'Les fléchisseurs de hanche sont souvent trop courts chez les personnes sédentaires. Cet étirement est fondamental.'),
('Pigeon Pose', 'Posture du pigeon', 'pigeon-pose', ARRAY['glutes','hip_abductors'], ARRAY['hip_flexors'], 'bodyweight', 'mobility', 'legs', 2, 'Jambe avant fléchie devant soi, jambe arrière tendue. Descends sur les avant-bras ou pose le front sur les mains. Maintiens 1-2 minutes.', 'Un des meilleurs étirements pour le piriforme et les fessiers. Fait à chaque fin de séance jambes.'),
('World''s Greatest Stretch', 'Le grand étirement mondial', 'worlds-greatest-stretch', ARRAY['hip_flexors','glutes','upper_back'], ARRAY['hamstrings','shoulders'], 'bodyweight', 'mobility', 'core', 2, 'En fente avant, pose la main du côté de la jambe avant au sol. Tourne le coude vers le bas puis lève le bras vers le plafond. Reviens. 5 reps par côté.', 'Exercice de mobilité complet qui touche toute la chaîne musculaire. Parfait en échauffement avant n''importe quelle séance.'),
('Thoracic Rotation', 'Rotation thoracique', 'thoracic-rotation', ARRAY['upper_back'], ARRAY['obliques'], 'bodyweight', 'mobility', 'core', 1, 'À quatre pattes ou assis. Une main derrière la tête. Tourne le coude vers le plafond en suivant avec le regard. Reviens. 10 reps par côté.', 'Améliore la mobilité thoracique souvent réduite par la sédentarité. Essentiel pour les mouvements au-dessus de la tête.'),
('Cat-Cow', 'Chat-Vache', 'cat-cow', ARRAY['lower_back'], ARRAY['core'], 'bodyweight', 'mobility', 'core', 1, 'À quatre pattes. Alterne entre creuser le dos (vache) et arrondir le dos (chat) en synchronisant avec la respiration.', 'Mobilisation de toute la colonne vertébrale. Excellent en échauffement ou en fin de séance. Très doux.'),
('Child''s Pose', 'Posture de l''enfant', 'childs-pose', ARRAY['lower_back'], ARRAY['lats','glutes'], 'bodyweight', 'mobility', 'core', 1, 'À genoux, assied les fesses sur les talons. Étire les bras devant sur le sol. Respire profondément et relâche.', 'Étirement doux pour le bas du dos. Parfait pour décompresser la colonne après des exercices de dos.'),
('Downward Dog', 'Chien tête en bas', 'downward-dog', ARRAY['hamstrings','calves'], ARRAY['lower_back','shoulders'], 'bodyweight', 'mobility', 'core', 1, 'Position de pompe. Pousse les hanches vers le haut et l''arrière pour former un triangle. Talon vers le sol, tête entre les bras.', 'Étirement complet de la chaîne postérieure. Excellent pour les coureurs et après des séances de jambes.'),
('90-90 Hip Stretch', 'Étirement 90-90 de hanche', '90-90-hip-stretch', ARRAY['hip_abductors','hip_flexors'], ARRAY['glutes'], 'bodyweight', 'mobility', 'legs', 2, 'Assis au sol, deux jambes à 90° (une devant, une sur le côté). Penche vers la jambe avant, maintiens. Puis tourne vers la jambe de côté.', 'Améliore la rotation externe et interne de hanche. Indispensable pour améliorer le squat et la course.'),
('Couch Stretch', 'Étirement du canapé', 'couch-stretch', ARRAY['hip_flexors','quads'], ARRAY[]::text[], 'bodyweight', 'mobility', 'legs', 2, 'Pied contre un mur ou un canapé, genou au sol (comme une fente). Monte le buste droit. Maintiens 2 minutes par côté.', 'Étirement profond du quadriceps et du fléchisseur de hanche. Très efficace après une longue journée assise.'),
('Jefferson Curl', 'Curl Jefferson', 'jefferson-curl', ARRAY['lower_back','hamstrings'], ARRAY[]::text[], 'bodyweight', 'mobility', 'core', 3, 'Debout sur une box, poids dans les mains. Arrondis progressivement la colonne du haut vers le bas. Descends le plus bas possible. Remonte vertèbre par vertèbre.', 'Étirement actif de toute la colonne et de la chaîne postérieure. Commence sans poids. Mouvement de santé avancé.'),
('Shoulder Dislocate', 'Dislocateur d''épaule', 'shoulder-dislocate', ARRAY['shoulders','chest'], ARRAY['lats'], 'band', 'mobility', 'push', 2, 'Élastique tenu à deux mains très large. Passe l''élastique devant vers l''arrière sur toute l''amplitude possible. Prise plus serrée = plus difficile.', 'Améliore la mobilité des épaules. Commence avec une prise TRÈS large. Réduit l''écartement progressivement au fil des semaines.'),
('Thoracic Extension', 'Extension thoracique', 'thoracic-extension', ARRAY['upper_back'], ARRAY[]::text[], 'bodyweight', 'mobility', 'core', 1, 'Assis, foam roller sous les omoplates. Laisse la tête descendre vers l''arrière. Remonte. Déplace le foam roller de haut en bas.', 'Mobilise la colonne thoracique et contre-balance l''arrondi dû à la position assise. Fait-le chaque jour.'),
('Ankle Circle', 'Cercle de cheville', 'ankle-circle', ARRAY['calves'], ARRAY[]::text[], 'bodyweight', 'mobility', 'legs', 1, 'Assis ou debout sur une jambe. Fait de grands cercles avec la cheville dans les deux sens. 10 cercles par sens.', 'Améliore la mobilité de cheville essentielle pour un bon squat et la prévention des entorses.'),
('Hip Circle', 'Cercle de hanche', 'hip-circle', ARRAY['hip_abductors','hip_flexors'], ARRAY['glutes'], 'bodyweight', 'mobility', 'legs', 1, 'Debout, mains sur les hanches. Fait de grands cercles avec les hanches dans les deux sens. Ample et lent.', 'Excellent échauffement pour les hanches. Active les muscles stabilisateurs de manière dynamique.'),

-- ══════════════════════════════════════════
-- OLYMPIQUE / OLYMPIC LIFTING
-- ══════════════════════════════════════════
('Power Clean', 'Épaulé de force', 'power-clean', ARRAY['quads','hamstrings','glutes'], ARRAY['traps','shoulders','calves'], 'barbell', 'compound', 'pull', 5, 'Départ au sol, triple extension (chevilles, genoux, hanches). Tire la barre vers le haut en haussant les épaules. Attrape en position de squat partiel.', 'Mouvement très technique. Apprends d''abord le deadlift, puis le high pull, puis le power clean complet.'),
('Hang Clean', 'Épaulé suspendu', 'hang-clean', ARRAY['hamstrings','glutes','quads'], ARRAY['traps','shoulders'], 'barbell', 'compound', 'pull', 4, 'Départ barre à mi-cuisse. Triple extension explosive. Attrape la barre en position frontale sur les épaules.', 'Plus simple que depuis le sol car élimine la première traction. Excellent pour développer la puissance.'),
('Push Jerk', 'Jeté poussé', 'push-jerk', ARRAY['shoulders','front_delt'], ARRAY['quads','triceps'], 'barbell', 'compound', 'push', 4, 'Barre sur les épaules. Légère flexion des jambes, pousse explosif vers le haut, plonge sous la barre bras tendus, rattrape debout ou en fente.', 'Permet de soulever plus lourd que le strict press. Mouvement de force athlétique complet.'),
('Clean Pull', 'Tiré d''épaulé', 'clean-pull', ARRAY['hamstrings','glutes','quads'], ARRAY['traps','calves'], 'barbell', 'compound', 'pull', 4, 'Comme le power clean mais sans attraper la barre. Monte la barre jusqu''aux hanches en triple extension maximale.', 'Exercice d''assistance pour renforcer la traction olympique. Permet des charges plus lourdes qu''un clean complet.'),
('Hang Snatch', 'Arraché suspendu', 'hang-snatch', ARRAY['quads','hamstrings','glutes'], ARRAY['shoulders','traps'], 'barbell', 'compound', 'pull', 5, 'Barre à mi-cuisse, prise très large. Extension explosive et tire la barre au-dessus de la tête en un mouvement continu.', 'Très technique. Commence avec une prise overhead squat pour t''habituer à la position finale.'),

-- ══════════════════════════════════════════
-- CARDIO
-- ══════════════════════════════════════════
('Assault Bike', 'Vélo Assault', 'assault-bike', ARRAY['cardio'], ARRAY['chest','shoulders','quads'], 'machine', 'cardio', 'core', 3, 'Pédale et pousse/tire les poignées simultanément. Corps entier en action. Parfait pour des intervalles à haute intensité.', 'Une des machines de cardio les plus exigeantes. 10 secondes à fond suffisent pour épuiser n''importe qui.'),
('Rowing Machine', 'Rameur', 'rowing-machine', ARRAY['lats','mid_back'], ARRAY['legs','biceps','core'], 'machine', 'cardio', 'pull', 2, 'Pousse avec les jambes d''abord, penche légèrement le buste en arrière, puis tire la poignée vers le ventre. Inverse le mouvement pour revenir.', 'Un des meilleurs cardio full-body. Technique : 60% jambes, 20% dos, 20% bras. Ne tire pas d''abord avec les bras.'),
('Stairmaster', 'Monte-escalier', 'stairmaster', ARRAY['cardio','quads'], ARRAY['glutes','calves'], 'machine', 'cardio', 'legs', 2, 'Monte les marches en maintenant une cadence constante. Garde le dos droit, ne t''appuie pas sur les rambardes.', 'Excellent cardio qui protège les genoux contrairement à la course. Les rambardes faussent l''effort, ne t''y appuie pas.'),
('Elliptical', 'Elliptique', 'elliptical', ARRAY['cardio'], ARRAY['quads','glutes','shoulders'], 'machine', 'cardio', 'core', 1, 'Mouvement elliptique combinant jambes et bras. Ajuste la résistance et l''inclinaison pour varier l''intensité.', 'Cardio à faible impact, idéal si tu as des douleurs de genoux ou de chevilles. Très complet si tu utilises aussi les bras.'),
('Box Jump', 'Saut sur box', 'box-jump', ARRAY['quads','glutes'], ARRAY['calves','hamstrings'], 'bodyweight', 'cardio', 'legs', 3, 'Debout face à la box. Demi-squat, bras en arrière, saute explosiviment sur la box en atterrissant avec les genoux fléchis.', 'Développe la puissance explosive des jambes. Commence avec une box basse (30 cm). Descends en marchant, pas en sautant.'),
('Burpee', 'Burpee', 'burpee', ARRAY['cardio','chest'], ARRAY['quads','shoulders','core'], 'bodyweight', 'cardio', 'core', 3, 'Debout, descends en squat, pose les mains au sol, saute les pieds en arrière (position pompe), pompe, ramène les pieds, saute en l''air bras levés.', 'Exercice full-body et cardio intense. Il n''y a pas de mauvaise forme pour un burpee, mais une bonne forme te permettra d''en faire plus.'),
('Jumping Jacks', 'Sauts étoiles', 'jumping-jacks', ARRAY['cardio'], ARRAY['shoulders','hip_abductors'], 'bodyweight', 'cardio', 'core', 1, 'Debout, saute en écartant les jambes et les bras simultanément. Reviens à la position initiale. Mouvement fluide et rythmé.', 'Idéal pour l''échauffement cardiovasculaire. Simple et efficace pour élever la fréquence cardiaque rapidement.'),
('Jump Squat', 'Squat sauté', 'jump-squat', ARRAY['quads','glutes'], ARRAY['calves','core'], 'bodyweight', 'cardio', 'legs', 2, 'Descends en squat partiel, pousse explosiviment en sautant le plus haut possible. Atterris avec les genoux fléchis.', 'Développe la puissance et le cardio simultanément. Attention à l''atterrissage : toujours genou fléchi pour absorber l''impact.'),
('Bear Crawl', 'Marche de l''ours', 'bear-crawl', ARRAY['core','shoulders'], ARRAY['chest','quads'], 'bodyweight', 'cardio', 'core', 2, 'À quatre pattes, genoux décollés de 5 cm du sol. Avance en bougeant bras et jambe opposés simultanément. Corps parallèle au sol.', 'Excellent pour le gainage dynamique et la coordination. Les genoux ne doivent jamais toucher le sol.'),
('Battle Rope Waves', 'Ondes cordes de combat', 'battle-rope-waves', ARRAY['shoulders','core'], ARRAY['biceps','triceps'], 'bodyweight', 'cardio', 'core', 3, 'Une extrémité de la corde dans chaque main. Crée des ondes en alternant les bras de haut en bas de manière explosive.', 'Cardio très intense qui cible les épaules et le core. 20 secondes à fond + 40 secondes de repos = HIIT parfait.'),

-- ══════════════════════════════════════════
-- KETTLEBELL
-- ══════════════════════════════════════════
('Turkish Get-Up', 'Levé turc', 'turkish-get-up', ARRAY['core','shoulders'], ARRAY['glutes','triceps'], 'kettlebell', 'compound', 'core', 4, 'Allongé, kettlebell bras tendu. Passe progressivement de la position couchée à debout en maintenant le kettlebell overhead, puis redescends.', 'L''exercice le plus complet qui soit. Commence avec AUCUN poids pour apprendre le mouvement. Lent et contrôlé.'),
('Kettlebell Snatch', 'Arraché kettlebell', 'kettlebell-snatch', ARRAY['shoulders','glutes','hamstrings'], ARRAY['core','traps'], 'kettlebell', 'compound', 'pull', 4, 'Balancé entre les jambes, extension de hanche explosive, tire le kettlebell vers le haut et fais pivoter sous pour le recevoir bras tendu.', 'Mouvement très technique. Le poignet doit faire une rotation au dernier moment pour éviter de claquer la cloché sur le poignet.'),
('Kettlebell Clean', 'Épaulé kettlebell', 'kettlebell-clean', ARRAY['hamstrings','glutes','shoulders'], ARRAY['core','biceps'], 'kettlebell', 'compound', 'pull', 3, 'Balancé entre les jambes, extension de hanche, tire le kettlebell en position rack (cloché contre l''avant-bras, coude près du corps).', 'La clé est de garder le kettlebell près du corps. Le balancement doit venir des hanches, pas des bras.'),
('Kettlebell Windmill', 'Moulin à vent KB', 'kettlebell-windmill', ARRAY['core','shoulders'], ARRAY['glutes','hamstrings'], 'kettlebell', 'compound', 'core', 3, 'Kettlebell bras tendu au-dessus. Descends la main libre vers le sol en gardant le regard sur le kettlebell. Remonte.', 'Excellent pour la mobilité d''épaule et le gainage latéral. Le regard vers le kettlebell est obligatoire.'),
('Kettlebell Goblet Squat', 'Squat goblet KB', 'kettlebell-goblet-squat', ARRAY['quads','glutes'], ARRAY['core','upper_back'], 'kettlebell', 'compound', 'legs', 2, 'Tiens la cloche à deux mains contre la poitrine. Descends en squat profond en gardant le dos droit. Pousse les genoux avec les coudes.', 'Excellent pour apprendre le squat avec une bonne posture. Le poids à l''avant aide à rester droit.'),
('Kettlebell Sumo Deadlift', 'Soulevé sumo KB', 'kettlebell-sumo-deadlift', ARRAY['glutes','hamstrings'], ARRAY['quads','lower_back'], 'kettlebell', 'compound', 'legs', 2, 'Kettlebell entre les pieds, position large. Soulève la cloche en poussant le sol, dos droit, fessiers contractés en haut.', 'Variante accessible du soulevé de terre sumo. Parfait pour les débutants ou en complément des exercices au sol.'),
('Bottoms-Up Press', 'Développé KB inversé', 'bottoms-up-kettlebell-press', ARRAY['shoulders'], ARRAY['triceps','core'], 'kettlebell', 'compound', 'push', 3, 'Tiens le kettlebell par la poignée, cloche vers le haut (inversé). Stabilise et pousse vers le haut. Nécessite une grande stabilité.', 'Position instable qui renforce les rotateurs de l''épaule et améliore la proprioception. Commence très léger.'),

-- ══════════════════════════════════════════
-- FONCTIONNEL / FARMER CARRIES
-- ══════════════════════════════════════════
('Farmer''s Walk', 'Marche du fermier', 'farmers-walk', ARRAY['traps','forearms'], ARRAY['core','quads','calves'], 'dumbbell', 'compound', 'carry', 2, 'Haltères ou kettlebells lourds dans chaque main. Marche en gardant le corps droit, épaules en arrière, pas régulier.', 'Un des meilleurs exercices fonctionnels. Renforce les trapèzes, la prise et le core simultanément. Lourd et court.'),
('Suitcase Carry', 'Portage valise', 'suitcase-carry', ARRAY['core','obliques'], ARRAY['traps','forearms'], 'dumbbell', 'compound', 'carry', 2, 'Un seul haltère ou kettlebell dans une main. Marche en résistant à l''inclinaison latérale. Corps parfaitement droit.', 'Renforce les obliques de manière anti-latérale-flexion. Plus difficile qu''il n''y paraît. Charge du côté le plus faible d''abord.'),
('Overhead Carry', 'Portage au-dessus de la tête', 'overhead-carry', ARRAY['shoulders','core'], ARRAY['traps'], 'dumbbell', 'compound', 'carry', 3, 'Haltère bras tendu au-dessus de la tête. Marche en maintenant la stabilité du bras tendu. Core engagé en permanence.', 'Renforce la stabilité de l''épaule et le gainage. Si le bras tremble, réduis le poids.'),
('TRX Row', 'Rowing TRX', 'trx-row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'bodyweight', 'compound', 'pull', 2, 'Sangles TRX à longueur de bras. Corps incliné en arrière, pieds devant. Tire le corps vers les poignées en gardant les coudes près du corps.', 'Plus tu es horizontal, plus c''est difficile. Excellent pour ceux qui ne font pas encore de tractions.'),
('TRX Push-Up', 'Pompe TRX', 'trx-push-up', ARRAY['chest'], ARRAY['triceps','front_delt','core'], 'bodyweight', 'compound', 'push', 3, 'Pieds dans les sangles TRX, mains au sol. Pompe classique avec les jambes suspendues. L''instabilité engage fortement le core.', 'Bien plus difficile qu''une pompe normale. Le core travaille intensément pour stabiliser. Commence les pieds haut et abaisse progressivement.'),
('TRX Squat', 'Squat TRX', 'trx-squat', ARRAY['quads','glutes'], ARRAY['core'], 'bodyweight', 'compound', 'legs', 1, 'Sangles TRX à hauteur de poitrine, face à l''ancrage. Descends en squat en utilisant légèrement les sangles pour l''équilibre.', 'Parfait pour apprendre le squat avec une bonne posture. Les sangles permettent de descendre plus bas sans perdre l''équilibre.'),
('Med Ball Slam', 'Lancer ballon médical', 'med-ball-slam', ARRAY['core','lats'], ARRAY['shoulders','abs'], 'bodyweight', 'cardio', 'core', 2, 'Balle médicale au-dessus de la tête. Lance-la au sol de toutes tes forces. Attrape-la ou ramasse-la. Recommence.', 'Excellent pour développer la puissance et évacuer le stress. Mouvement explosif qui engage tout le corps.'),

-- ══════════════════════════════════════════
-- AVANT-BRAS / FOREARMS
-- ══════════════════════════════════════════
('Wrist Curl', 'Curl de poignet', 'wrist-curl', ARRAY['forearms'], ARRAY[]::text[], 'barbell', 'isolation', 'pull', 1, 'Avant-bras posés sur les genoux, paumes vers le haut. Fléchis les poignets vers le haut en tenant la barre ou les haltères. Redescends lentement.', 'Renforce les fléchisseurs du poignet. Important pour la prise et la prévention des blessures de coude.'),
('Reverse Wrist Curl', 'Extension de poignet', 'reverse-wrist-curl', ARRAY['forearms'], ARRAY[]::text[], 'barbell', 'isolation', 'pull', 1, 'Avant-bras posés sur les genoux, paumes vers le bas. Étends les poignets vers le haut. Redescends lentement.', 'Renforce les extenseurs du poignet, souvent négligés. Aide à prévenir l''épicondylite (tennis elbow).'),
('Dead Hang', 'Suspension statique', 'dead-hang', ARRAY['forearms','lats'], ARRAY['biceps'], 'bodyweight', 'isolation', 'pull', 2, 'Suspendu à la barre, prise pronation, bras complètement tendus. Maintiens aussi longtemps que possible. Relax les épaules.', 'Excellent pour la décompression de la colonne, la prise et la mobilité des épaules. Vise 30-60 secondes.'),
('Plate Pinch', 'Pince de disque', 'plate-pinch', ARRAY['forearms'], ARRAY[]::text[], 'bodyweight', 'isolation', 'pull', 2, 'Tiens un ou deux disques entre le pouce et les autres doigts, face lisse vers l''extérieur. Maintiens aussi longtemps que possible.', 'Renforce la prise par la pointe des doigts. Excellent pour l''escalade et tous les sports de saisie.'),
('Towel Pull-Up', 'Traction sur serviette', 'towel-pull-up', ARRAY['biceps','lats','forearms'], ARRAY['mid_back'], 'bodyweight', 'compound', 'pull', 4, 'Passe une serviette sur la barre. Une extrémité dans chaque main. Effectue des tractions normales. La serviette bouge et sollicite la prise.', 'Extrêmement difficile pour la prise. Excellent pour développer la force des avant-bras en prise sur corde.'),

-- ══════════════════════════════════════════
-- COU / NECK
-- ══════════════════════════════════════════
('Neck Flexion', 'Flexion du cou', 'neck-flexion', ARRAY['abs'], ARRAY[]::text[], 'bodyweight', 'isolation', 'pull', 1, 'Allongé sur le ventre ou avec une resistance légère. Penche la tête vers la poitrine contre résistance. Lentement.', 'Renforce les muscles fléchisseurs du cou. Important pour les sportifs de contact. Commence sans poids.'),
('Neck Extension', 'Extension du cou', 'neck-extension', ARRAY['traps'], ARRAY[]::text[], 'bodyweight', 'isolation', 'pull', 1, 'Allongé sur le ventre ou assis. Penche la tête vers l''arrière contre résistance légère. Maintiens 2 secondes.', 'Renforce les extenseurs du cou. Contre-balance les tractions (chin-up) qui sollicitent les fléchisseurs.'),
('Neck Lateral Flexion', 'Flexion latérale du cou', 'neck-lateral-flexion', ARRAY['traps'], ARRAY[]::text[], 'bodyweight', 'isolation', 'pull', 1, 'Assis droit. Penche la tête vers l''épaule contre la résistance de la main opposée. Lentement dans les deux sens.', 'Renforce les muscles latéraux du cou. Fait des 2 côtés pour équilibrer. Très léger, ce n''est pas une compétition.'),

-- ══════════════════════════════════════════
-- PLYOMÉTRIE / ATHLETISME
-- ══════════════════════════════════════════
('Broad Jump', 'Saut en longueur', 'broad-jump', ARRAY['quads','glutes'], ARRAY['calves','hamstrings'], 'bodyweight', 'cardio', 'legs', 3, 'Demi-squat, bras en arrière. Saute le plus loin possible en projetant les bras vers l''avant. Atterris sur les deux pieds genou fléchis.', 'Mesure la puissance horizontale. Excellent pour les sportifs. Atterrissage soft et contrôlé toujours.'),
('Lateral Bound', 'Bond latéral', 'lateral-bound', ARRAY['glutes','quads'], ARRAY['calves','hip_abductors'], 'bodyweight', 'cardio', 'legs', 3, 'Saute latéralement sur un pied et atterris en équilibre sur l''autre pied. Maintiens 1 seconde puis recommence de l''autre côté.', 'Développe la puissance latérale et la proprioception. Essentiel pour tous les sports avec changements de direction.'),
('Lateral Shuffle', 'Glissement latéral', 'lateral-shuffle', ARRAY['cardio','hip_abductors'], ARRAY['quads','glutes'], 'bodyweight', 'cardio', 'core', 2, 'Position athlétique (genoux fléchis). Déplace-toi latéralement rapidement en poussant avec le pied extérieur. Pieds ne se croisent pas.', 'Mouvement défensif fondamental dans de nombreux sports. Maintiens les genoux fléchis tout au long.'),
('Depth Jump', 'Saut en profondeur', 'depth-jump', ARRAY['quads','glutes'], ARRAY['calves'], 'bodyweight', 'cardio', 'legs', 4, 'Descends d''une box (sans sauter). Dès que les pieds touchent le sol, re-sautez immédiatement le plus haut possible.', 'Exercice pliométrique avancé. Le temps de contact au sol doit être minimal. Augmente la puissance réactive.'),

-- ══════════════════════════════════════════
-- FESSIERS COMPLÉMENTAIRES
-- ══════════════════════════════════════════
('Cable Pull-Through', 'Tirage câble entre les jambes', 'cable-pull-through', ARRAY['glutes','hamstrings'], ARRAY['lower_back'], 'cable', 'isolation', 'legs', 2, 'Dos à la poulie basse, corde entre les jambes. Penche-toi avec les hanches (hip hinge), laisse la corde partir entre les jambes, remonte en poussant les hanches.', 'Excellent pour apprendre le hip hinge et renforcer les fessiers. Moins de compression lombaire qu''un soulevé de terre.'),

-- ══════════════════════════════════════════
-- EXERCICES COMPOSÉS COMPLÉMENTAIRES
-- ══════════════════════════════════════════
('Zercher Squat', 'Squat Zercher', 'zercher-squat', ARRAY['quads','glutes'], ARRAY['biceps','core','upper_back'], 'barbell', 'compound', 'legs', 3, 'Barre dans les plis des coudes, bras croisés. Descends en squat profond. Le poids à l''avant oblige à rester très droit.', 'Intensément difficile pour les biceps et le dos supérieur. Commence très léger. Excellent pour la posture.'),
('Landmine Squat', 'Squat landmine', 'landmine-squat', ARRAY['quads','glutes'], ARRAY['core','upper_back'], 'barbell', 'compound', 'legs', 2, 'Barre coincée dans un angle, tiens l''extrémité à deux mains contre la poitrine. Descends en squat guidé par l''arc de la barre.', 'Le mouvement en arc aide à maintenir la position verticale du buste. Parfait si tu as du mal avec le squat classique.'),
('Snatch Grip Deadlift', 'Soulevé prise arraché', 'snatch-grip-deadlift', ARRAY['hamstrings','glutes'], ARRAY['upper_back','traps'], 'barbell', 'compound', 'legs', 4, 'Prise très large (comme pour l''arraché). Soulevé de terre normal mais avec cette prise. La barre monte plus haut et le dos travaille différemment.', 'Renforce les trapèzes et la mobilité des épaules en plus de la chaîne postérieure. Réduis le poids de 30% vs deadlift.'),
('Romanian Deadlift with Dumbbells', 'Soulevé roumain aux haltères', 'romanian-deadlift-dumbbells', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'dumbbell', 'isolation', 'legs', 2, 'Debout, haltères devant les cuisses. Penche-toi en avant avec le dos droit, haltères le long des jambes jusqu''à sentir l''étirement des ischios.', 'Les haltères permettent plus de liberté de mouvement que la barre. Excellent si tu débutes ou en complément.'),
('Barbell Hip Thrust', 'Hip Thrust barre', 'barbell-hip-thrust', ARRAY['glutes'], ARRAY['hamstrings','lower_back'], 'barbell', 'compound', 'legs', 2, 'Dos contre un banc, barre sur les hanches avec coussin. Pousse les hanches vers le haut en contractant les fessiers. Maintiens 2 secondes.', 'L''exercice roi pour les fessiers selon la recherche. Charge progressive possible. Protège bien les hanches avec un coussin.'),
('Incline Barbell Row', 'Rowing barre incliné', 'incline-barbell-row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', 'compound', 'pull', 3, 'Allongé face contre le banc incliné à 45°. Tire la barre vers le ventre. La poitrine soutenue élimine toute triche du dos.', 'Comme le chest-supported row mais avec une barre libre. Plus de liberté de mouvement et d''amplitude.'),
('Wide-Grip Pull-Up', 'Traction prise large', 'wide-grip-pull-up', ARRAY['lats'], ARRAY['biceps','rear_delt'], 'bodyweight', 'compound', 'pull', 4, 'Prise en pronation plus large que les épaules. Monte le menton au-dessus de la barre. La prise large cible davantage les grands dorsaux.', 'Développe la largeur du dos. Plus difficile que la prise normale. Amplitude réduite mais isolation des lats maximisée.'),
('Assisted Pull-Up', 'Traction assistée machine', 'assisted-pull-up', ARRAY['lats','biceps'], ARRAY['mid_back'], 'machine', 'compound', 'pull', 1, 'Genoux sur la plateforme de la machine d''assistance. Effectue des tractions, la machine soustrait une partie du poids du corps.', 'Parfait pour apprendre la traction. Réduis l''assistance progressivement jusqu''à ne plus en avoir besoin.'),
('Kettlebell Figure 8', 'Kettlebell chiffre 8', 'kettlebell-figure-8', ARRAY['core','obliques'], ARRAY['forearms','glutes'], 'kettlebell', 'compound', 'core', 2, 'Pieds écartés, kettlebell entre les jambes. Passe la cloche en 8 autour de tes jambes en alternant les mains. Reste en position basse.', 'Excellent pour la coordination et le gainage dynamique. Reste en position de demi-squat tout au long.'),
('Dumbbell Lateral Lunge', 'Fente latérale haltères', 'dumbbell-lateral-lunge', ARRAY['quads','glutes'], ARRAY['hip_abductors','hamstrings'], 'dumbbell', 'compound', 'legs', 2, 'Debout, fais un grand pas sur le côté. Descends en fléchissant le genou de la jambe qui a bougé, l''autre jambe tendue. Reviens.', 'Excellent pour la mobilité des hanches et le travail des adducteurs. Le genou doit rester dans l''axe du pied.'),
('Bulgarian Split Squat with Dumbbells', 'Fente bulgare aux haltères', 'bulgarian-split-squat-dumbbells', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', 'compound', 'legs', 3, 'Pied arrière sur un banc, haltères dans les mains. Descends la jambe arrière vers le sol en gardant le buste droit. Pousse avec la jambe avant.', 'Variante haltères plus accessible que la version barre. Permet plus de liberté de mouvement. Excellent unilatéral.'),
('Overhead Press with Dumbbells', 'Développé épaules haltères', 'overhead-press-dumbbells', ARRAY['front_delt','shoulders'], ARRAY['triceps','traps'], 'dumbbell', 'compound', 'push', 2, 'Assis ou debout, haltères à hauteur d''épaule. Pousse vers le haut jusqu''à extension complète. Redescends lentement.', 'Les haltères permettent plus de liberté que la barre et corrigent les déséquilibres. Prise neutre possible pour varier.')

ON CONFLICT (slug) DO NOTHING;
